POST http://localhost:8080/new_user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"firstName": "John", "lastName": "Smith"}

###

POST http://localhost:8080/new_user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"firstName": "James", "lastName": "Smith"}

###

POST http://localhost:8080/new_user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"firstName": "John", "lastName": "Wayne"}

###

PUT http://localhost:8080/edit_name/2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"firstName": "James", "lastName": "Smith The Second"}

###

PUT http://localhost:8080/del_friend/1/2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:8080/new_post
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"authorId": 1, "content":"This is post 1 by user 1"}

###

POST http://localhost:8080/new_post
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"authorId": 1, "content":"This is post 2 by user 1"}

###

POST http://localhost:8080/new_post
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"authorId": 3, "content":"This is post 1 by user 3"}

###

PUT http://localhost:8080/edit_post/6
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"authorId": 3, "content":"This is post 1 by user 3 but edited"}

###

POST http://localhost:8080/new_comment
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"authorId": 1, "rootPostId": 5, "content":"This is comment 1 by user 1 to post 4"}

###